import { ToastContainer } from 'react-toastify'
import Head from 'next/head'

import 'react-toastify/dist/ReactToastify.css'
import styles from './index.module.scss'

import { Calendar } from '@/components/Calendar'
import CrewhrContent from '@/components/CrewhrContent'
import { Header } from '@/components/Header/Header'

export default function Home() {
  return (
    <>
      <Head>
        <title>Free Employee Scheduling Software | CrewHR.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className={styles.mainContainer}>
        <div className={styles.container}>
          <div className={styles.wrapper}>
            <Header />
            <Calendar />
          </div>
          <CrewhrContent />
        </div>
        {/* <CrispChat /> */}
        <ToastContainer position="top-center" containerId={'Global'} />
      </main>
    </>
  )
}
